### ISSUE TITLE
Upload failed status 201

### ISSUE THREAD

**Issue by blackat** [skhatri/grunt-nexus-deployer#18]
Hi,
I have configured the grunt plugin, installed curl and when I run the plugin I get this error
>> Artifact Upload failed
>> Status code 201 for http://xx

on Nexus the groupId folders have been correctly created, maven-metadata.xml has been created as the http code 201 says, but the arifact upload failed, how can I have more log details? do you know what happens?

I am running the command as grunt nexusDeployer -verbose

Thanks a lot for the attention.

**Comment by kwiatkk1** [comment]
It's probably because of condition in https://github.com/skhatri/grunt-nexus-deployer/blob/master/tasks/lib/index.js#L91

If we recived 2xx status then it implies that it's a success. So the code should be:
```
if (status.substring(0,1) == "2" || code == 0) {
    cb(null, "Ok");
} else  {
    cb("Status code " + status + " for " + targetUri, null);
}
```

**Comment by stefanrieken** [comment]
I believe the current code is correctly checking for either 200 or 201. However, it also checks if code == 0 (the return code of the childProcess started earlier).

It would appear that since a newer version of node (or whatever it is that provides the childProcess functionality) the return code is no longer 0.

That is, I had no problems before updating dependencies; I have them now; and I don't have them anymore if I remove the "code == 0" check.

**Comment by ezeed** [comment]
@blackat @kwiatkk1 @stefanrieken We have different 2 parameters: "status" (provided by the HTTP Request status response, in this case 2xx ) and "code" (provided by `curl` command response, with this [Error Codes](https://curl.haxx.se/libcurl/c/libcurl-errors.html) ) . I had the same case, HTTP Request status 201 and "Artifact upload fail". In my case the "code" was 23 'CURLE_WRITE_ERROR'. 
In Arch Linux (4.5.1-1-ARCH), for some reason, don't have permission to write in `/dev/stderr` and this is default value of the `curl` parameter `--output` in [this options](https://github.com/skhatri/grunt-nexus-deployer/blob/master/tasks/lib/index.js#L65) . 
Check the code of the curl response and try to trace the error. But is necessary more log and error description because I really don't know why with a 201 HTTP status code the upload just fail.

**Comment by skhatri** [comment]
0.0.8 has this change. thanks
